- hosts: all
  environment:
    PATH: "{{ prefix }}/bin:{{ ansible_env.PATH }}"
    PYTHONUSERBASE: "{{ prefix }}"
  vars:
    njobs: "{{ansible_processor_count * ansible_processor_cores * 2}}"
  roles:
    - curl
    - cmake
    - python
    - opencv
    - cuda
  tasks:
    - name: make git/completion
      file:
        path: "{{ prefix }}/share/git/completion"
        state: directory
    - name: git-prompt
      get_url:
        url: https://raw.githubusercontent.com/git/git/master/contrib/completion/git-prompt.sh
        dest: "{{ prefix }}/share/git/completion"
    - name: tmux
      get_url:
        url: https://gist.githubusercontent.com/Hakuyume/e764018bc7dc2072dba43b02c7b489b9/raw/80c12398e45d2c66e871523d394273b78bba20bb/.tmux.conf
        dest: "{{ prefix }}/tmux.conf"
    - name: bashrc
      template:
        src: bashrc.bash
        dest: "{{ prefix }}/bashrc.bash"
