- name: find version
  command: "grep 'OpenBLAS {{ openblas_version }}' {{ prefix }}/include/openblas_config.h"
  register: result
  changed_when: false
  failed_when: false
- name: check version
  set_fact:
    installed: "{{ result.rc == 0 }}"

- name: fetch source
  get_url:
    url: "http://github.com/xianyi/OpenBLAS/archive/v{{ openblas_version }}.tar.gz"
    dest: "{{ cache_dir }}/openblas-{{ openblas_version }}.tar.gz"
  when: not installed
- name: make tempdir
  tempfile:
    state: directory
  register: tempdir
  when: not installed
- name: extract source
  unarchive:
    src: "{{ cache_dir }}/openblas-{{ openblas_version }}.tar.gz"
    dest: "{{ tempdir.path }}"
    remote_src: yes
  when: not installed
- name: build
  command: "make -j{{ njobs }}"
  args:
    chdir: "{{ tempdir.path }}/OpenBLAS-{{ openblas_version }}"
  when: not installed
- name: install
  command: "make PREFIX={{ prefix }} install"
  args:
    chdir: "{{ tempdir.path }}/OpenBLAS-{{ openblas_version }}"
  when: not installed
- name: create symlink
  file:
    src: libopenblas.so
    dest: "{{ prefix }}/lib/lib{{ item[0] }}.so{{ item[1] }}"
    state: link
  with_nested:
    - ['blas', 'cblas', 'lapack', 'lapacke']
    - ['', ".{{ lapack_version[0] }}", ".{{ lapack_version|join('.') }}"]
  when: not installed
