- name: fetch path
  command: which cmake
  register: result
  changed_when: false
  failed_when: false
- name: check path
  set_fact:
    installed: "{{ result.stdout == prefix + '/bin/cmake' }}"
- name: fetch version
  shell: cmake --version | head -n1 | perl -anE 'say $F[-1]'
  register: result
  changed_when: false
  when: installed
- name: check version
  set_fact:
    installed: "{{ result.stdout == cmake_version }}"
  when: installed

- name: make tempdir
  tempfile:
    state: directory
  register: tempdir
  when: not installed
- name: fetch source
  unarchive:
    src: "https://github.com/Kitware/CMake/archive/v{{ cmake_version }}.tar.gz"
    dest: "{{ tempdir.path }}"
    remote_src: yes
  when: not installed
- name: make builddir
  file:
    path: "{{ tempdir.path }}/build"
    state: directory
  when: not installed
- name: configure
  command: |
    ../CMake-{{ cmake_version }}/bootstrap \
        --prefix={{ prefix }}
  args:
    chdir: "{{ tempdir.path }}/build"
  when: not installed
- name: build
  command: "make -j{{ njobs }}"
  args:
    chdir: "{{ tempdir.path }}/build"
  when: not installed
- name: install
  command: make install
  args:
    chdir: "{{ tempdir.path }}/build"
  when: not installed
