- name: fetch driver version
  shell: 'nvidia-smi | perl -n0E "say m/(?<=Driver Version: )(\d+)/"'
  register: result
  changed_when: false
- name: set package versions
  set_fact:
    "{{ item }}": "{{ driver_versions[result.stdout|int][item] }}"
  with_items:
    - cuda_version
    - cuda_installer
    - cudnn_archive

- name: fetch path
  command: which nvcc
  environment:
    PATH: "{{ prefix }}/cuda/bin:{{ ansible_env.PATH }}"
  register: result
  changed_when: false
  failed_when: false
- name: check path
  set_fact:
    installed: "{{ result.stdout == prefix + '/cuda/bin/nvcc' }}"
- name: fetch version
  command: "perl -anE 'say $F[-1]' {{ prefix }}/cuda/version.txt"
  register: result
  changed_when: false
  when: installed
- name: check version
  set_fact:
    installed: "{{ result.stdout == cuda_version }}"
  when: installed

- name: copy cuda installer
  copy:
    src: "{{ cuda_installer }}"
    dest: "{{ cache_dir }}"
  when: not installed
- name: install cuda
  command: "sh {{ cache_dir }}/{{ cuda_installer }} --silent --toolkit --toolkitpath={{ prefix }}/cuda"
  when: not installed

- name: copy cudnn archive
  copy:
    src: "{{ cuda_installer }}"
    dest: "{{ cache_dir }}"
  when: not installed
- name: install cudnn
  unarchive:
    src: "{{ cache_dir }}/{{ cudnn_archive }}"
    dest: "{{ prefix }}"
    remote_src: yes
  when: not installed
